config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
      post :approve, :decline
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts,only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :pictures
  resources :messages do
    member do
      get :inbox, :outbox
    end
  end

 

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
	end

	def show
		@user = User.find_by(user_name: params[:id])
		@pictures = current_user.pictures.paginate(page: params[:page])
	end

	def new
	end

	def create
      @user = User.find_by(user_name: params[:id])
      @picture = current_user.pictures.build(picture_params)
      if @picture.save
      	redirect_to picture_path(current_user)
      else
      redirect_to root_url
      end
	end

	def edit
	end

	def update
	end

	def destroy
		
	end
private
def picture_params
  	params.require(:picture).permit(:name, :description, :image)
  end

  def correct_user
      @user = User.find_by(user_name: params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_picture.html.erb
<div class="row reply">
  <div class="col-sm-6 col-md-8">
  	<div class="caption center"><h5><%= picture.name %></h5></div>
    <div class="thumbnail">
      <%= image_tag( picture.image_url.to_s, size: "180x120", id: "editimage#{picture.id}") %>
      <div class="caption">
      	
  <span class="content "><%= picture.description %></span>
        <% if current_user?(picture.user) %>
   <div class="center"> <%= link_to "delete", picture, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: picture.name %> |
    <%= link_to "edit", '#' %>

<p><input type='image' src='http://images.aviary.com/images/edit-photo.png' value='Edit photo' onclick="return launchEditor('editimage<%= picture.id %>', 'https://guarded-lake-3340.herokuapp.com/pictures/sweetheart/1.jpg');" /></p>
   

  <% end %>
</div>
      </div>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<p>testing</p>

app/views/pictures/new.html.erb
<% provide(:title, "New Pictures") %>
<h1>Add A New Picture</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:picture, url: pictures_path, :html => {:multipart => true}) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.file_field :image %>

      <%= f.submit "Add your new picture", class: "btn mybtn btn-lg btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/pictures/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-3">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %><br/>
        <%= @email %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      
        <%= if current_user == @user
     link_to 'Add new pictures', new_picture_path # render partial: "product", collection: @products
    end
       %>
    </section>
  </aside>
	<div class="col-md-9">
		
	    <% if @user.pictures.any? %>
	      <h3>Pictures (<%= @user.pictures.count %>)</h3>
	      <ol class="microposts">
	        <%= render @pictures %>
	      </ol>
	      <%= will_paginate @pictures %>
	    <% end %>
	  </div>
  
</div>